---
title: "temp dash"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r packages, include = FALSE}
library(ggplot2)
library(DT)
```

```{r data, include = FALSE}
data <- data.frame(v = rnorm(100))
```

Page 1
=============

sidebar {.sidebar data-width=330}
------------------

Sidebar

***

```{r}
numericInput("bin", "Bin:", 0.1, min = 0)
```

```{r}
sliderInput("range1", "Range:",
            min = 0,
            max = 1,
            value = c(0.1, 0.9),
            step = 0.1)
```


```{r}
sliderInput("range2", "Range:",
            min = 0,
            max = 1,
            value = c(0.1, 0.9),
            step = 0.1)
```

Row
---

### Price 1
    
```{r histogram_norm1}
renderPlot({
ch.h <- ggplot(data, aes(x = v)) + 
  geom_histogram(binwidth = input$bin,
                 color = "darkblue", 
                 fill = "lightblue") +
  xlab(" ") + ylab("Frequency")
ch.h
})
```

### Price 2

```{r histogram_norm2}
renderPlot({
ch.h <- ggplot(data, aes(x = v)) + 
  geom_histogram(binwidth = input$bin,
                 color = "darkblue", 
                 fill = "lightblue") +
  xlab(" ") + ylab("Frequency")
ch.h
})
```

### Price 3

```{r histogram_norm3}
renderPlot({
ch.h <- ggplot(data, aes(x = v)) + 
  geom_histogram(binwidth = input$bin,
                 color = "darkblue", 
                 fill = "lightblue") +
  xlab(" ") + ylab("Frequency")
ch.h
})
```

Row
---
    
### Price Summary 1

```{r}
renderTable({
data.frame(Stat = names(summary(data$v)),
           Value = round(as.numeric(summary(data$v)), 4))
})
```
    
### Price Summary 2
    
```{r}
renderTable({
data.frame(Stat = names(summary(data$v)),
           Value = round(as.numeric(summary(data$v)), 4))
})
```

### Price Summary 3
    
```{r}
renderTable({
data.frame(Stat = names(summary(data$v)),
           Value = round(as.numeric(summary(data$v)), 4))
})
```

page 2
======

sidebar {.sidebar}
------------------

```{r}

```

